build:
  build:
    image: node:5
    commands:
      - cp config-ci.json config.json
      - npm install || true
      - npm run build

publish:
  s3_sync:
    acl: public-read
    region: eu-central-1
    bucket: staging.2016.scala-italy.it
    access_key: $$S3_ACCESS_KEY
    secret_key: $$S3_SECRET_KEY
    source: build
    target: /
    delete: true
    when:
      branch: master
